all:
  children:
    windows:
      hosts:
        win-server:
          ansible_host: 192.168.19.133
          ansible_user: ISTA\ADMINISTRATEUR
          ansible_password: Azerty501
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986

    linux_servers:
      hosts:
        debian-server:
          ansible_host: 192.168.19.129
          ansible_user: teti
          ansible_ssh_private_key_file: /home/teti/.ssh/id_ed25519
        ubuntu-server:
          ansible_host: 192.168.19.132
        kali-attacker:
          ansible_host: 192.168.19.130

    bastion: # ← Nouveau groupe
      hosts:
        debian-server: # ← On pointe vers l'hôte existant

    firewalls:
      hosts:
        opnsense:
          ansible_host: 192.168.19.131
          ansible_connection: network_cli
          ansible_network_os: opnsense
