---
- name: Déploiement Prometheus + Node Exporter + Grafana
  hosts: monitoring_server  # Ton Ubuntu ou Debian dédié
  become: yes
  tasks:
    - name: Création répertoire Docker
      file:
        path: /opt/monitoring
        state: directory

    - name: Copie docker-compose.yml
      template:
        src: docker-compose-monitoring.yml.j2
        dest: /opt/monitoring/docker-compose.yml

    - name: Installation Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Lancement stack monitoring
      docker_compose:
        project_src: /opt/monitoring
        state: present
      notify: restart monitoring

  handlers:
    - name: restart monitoring
      docker_compose:
        project_src: /opt/monitoring
        restarted: yes